import { Product } from '../types';

export const allProducts: Product[] = [
  //not grouped yet
  {
    image: '/images/products/midi-size-banana-bread.jpg',
    name: 'Midi size banana bread with coconut topping',
    price: 1200,
    rating: 4.7,
    category: '',
    id: 1,
  },
  //birthday cakes
  {
    image: '/images/birthday-cakes-images/birthday-cake-1.jpg',
    name: '8inch by 9inch whipped cream cake',
    price: 35000,
    rating: 4.8,
    category: 'birthday-cakes',
    id: 2,
  },
  {
    image: '/images/birthday-cakes-images/birthday-cake-2.jpg',
    name: '8inch by 5inch buttercream cake',
    price: 22000,
    rating: 4.9,
    category: 'birthday-cakes',
    id: 3,
  },
  {
    image: '/images/birthday-cakes-images/birthday-cake-3.jpg',
    price: 45000,
    name: 'Birthday cake',
    category: 'birthday-cakes',
    rating: 4.9,
    id: 4,
  },
  {
    image: '/images/birthday-cakes-images/birthday-cake-4.jpg',
    name: 'Birthday cake',
    price: 35000,
    rating: 4.9,
    category: 'birthday-cakes',
    id: 5,
  },
  //juice
  {
    image: '/images/juice-images/juice-1.jpg',
    name: 'Kiddies juice Pack of 10',
    price: 7500,
    rating: 5,
    category: 'natural-fruit-juices',
    id: 6,
  },
  {
    image: '/images/juice-images/juice-2.jpg',
    name: 'Cold pressed kiddies fruit juice Pack of 10',
    price: 7500,
    rating: 4.8,
    category: 'natural-fruit-juices',
    id: 7,
  },
  {
    image: '/images/juice-images/juice-3.jpg',
    name: '500ml cold pressed fruit juices',
    price: 1500,
    rating: 4.8,
    category: 'natural-fruit-juices',
    id: 8,
  },
  {
    image: '/images/juice-images/juice-3.jpg',
    name: '500ml natural fruit juice variants | 1pack(12 pics)',
    price: 23400,
    rating: 4.5,
    category: 'natural-fruit-juices',
    id: 15,
  },
  {
    image: '/images/juice-images/juice-3.jpg',
    name: '500ml natural fruit juice variants | half-pack(6 pics)',
    price: 12000,
    rating: 4.9,
    category: 'natural-fruit-juices',
    id: 16,
  },
  {
    image: '/images/juice-images/juice-2.jpg',
    name: '250ml natural fruit juice variants (kiddies) | 1pack(12 pics)',
    price: 11800,
    rating: 4.6,
    category: 'natural-fruit-juices',
    id: 17,
  },
  {
    image: '/images/juice-images/juice-2.jpg',
    name: '250ml natural fruit juice variants (kiddies) | 100 pouches',
    price: 95000,
    rating: 4.5,
    category: 'natural-fruit-juices',
    id: 22,
  },
  {
    image: '/images/juice-images/juice-3.jpg',
    name: '250ml natural fruit juice variants | 100 bottles',
    price: 110000,
    rating: 4.9,
    category: 'natural-fruit-juices',
    id: 23,
  },
  {
    image: '/images/juice-images/juice-3.jpg',
    name: '500ml natural fruit juice variants | 100 bottles',
    price: 195000,
    rating: 4.8,
    category: 'natural-fruit-juices',
    id: 24,
  },
  //wedding cake
  {
    image: '/images/wedding-cakes-images/wedding-cake-1.jpg',
    name: 'Floral wedding cake',
    price: 300000,
    rating: 4.9,
    category: 'wedding-cakes',
    id: 9,
  },
  {
    image: '/images/wedding-cakes-images/wedding-cake-2.jpg',
    name: 'Traditional wedding cake',
    price: 250000,
    rating: 4.7,
    category: 'wedding-cakes',
    id: 10,
  },
  {
    image: '/images/wedding-cakes-images/wedding-cake-3.jpg',
    name: 'White wedding cake',
    price: 250000,
    rating: 4.7,
    category: 'wedding-cakes',
    id: 11,
  },
  {
    image: '/images/wedding-cakes-images/wedding-cake-4.jpg',
    name: 'Traditional wedding cake',
    price: 130000,
    rating: 5,
    category: 'wedding-cakes',
    id: 12,
  },
  //yogurt
  {
    image: '/images/yogurts-images/yogurt-1.jpg',
    name: '550ml parfait bowl',
    price: 3500,
    rating: 4.9,
    category: 'yogurts',
    id: 13,
  },
  {
    image: '/images/yogurts-images/yogurt-2.jpg',
    name: '10L parwait youghurt',
    price: 25000,
    rating: 4.7,
    category: 'yogurts',
    id: 14,
  },
  {
    image: '/images/yogurts-images/yogurt-2.jpg',
    name: '500ml tigernut milk | 1pack(12 pics)',
    price: 19600,
    rating: 4.7,
    category: 'yogurts',
    id: 18,
  },
  {
    image: '/images/yogurts-images/yogurt-2.jpg',
    name: '500ml tigernut milk | half-pack(6 pics)',
    price: 10200,
    rating: 4.4,
    category: 'yogurts',
    id: 19,
  },
  {
    image: '/images/yogurts-images/yogurt-2.jpg',
    name: '250ml tigernut milk | 100 bottles',
    price: 90000,
    rating: 4.6,
    category: 'yogurts',
    id: 20,
  },
  {
    image: '/images/yogurts-images/yogurt-2.jpg',
    name: '500ml tigernut milk | 100 bottles',
    price: 150000,
    rating: 4.8,
    category: 'yogurts',
    id: 21,
  },

  // { image: '/images/products-category-images/chin.png', name: 'Chins', id: 7 },
];

// export const products: Product[] = [
//   { image: '/images/products-category-images/cake.png', name: 'Cakes', id: 1 },
//   { image: '/images/products-category-images/pie.png', name: 'Pies', id: 2 },
//   {
//     image: '/images/products-category-images/doughnut.png',
//     name: 'Doughnuts',
//     id: 3,
//   },
//   {
//     image: '/images/products-category-images/shawarma.png',
//     name: 'Shawarmas',
//     id: 4,
//   },
//   {
//     image: '/images/products-category-images/pizza.png',
//     name: 'Pizzas',
//     id: 5,
//   },
//   {
//     image: '/images/products-category-images/parfait.png',
//     name: 'Parfaits',
//     id: 6,
//   },
//   { image: '/images/products-category-images/chin.png', name: 'Chins', id: 7 },
// ];
